### PR TITLE
Update google gemini for new gemini 1.5 pro and gemini 1.5 flash. 

### PR DESCRIPTION
**Pull request by Nghiauet**
What change 
New model gemini 1.5 is better and faster than gemini 1.0. ( and it also free) 
+ add option choose between difference gemini model
+ update "@google/generative-ai": to 0.11.2
+ Fix the error block because of safety
I have checked that it it run perfectly in 2 day.
This is image for extention after change 
image
image

### CODE REVIEW

**Comment by tudoujunha** [comment]
Thank you for your  pull request. I checked it out and adopted some of it.
https://github.com/tudoujunha/gemini-google-extension/releases/tag/v0.1.2
- Update gemini and openai models
- Change Gemini Safety settings to None

**Comment by Nghiauet** [comment]
I see it. Can you add me as a contributor in new release. I very please if have my name in it.

**Comment by tudoujunha** [comment]
No problem, I already added it.I didn't know it was a feature.

**Comment by Nghiauet** [comment]
Thanks you. <3

**Pull request closed without merging**
